pool:
 vmImage: 'ubuntu-latest'

variables:
 tier: web
 target: dev

steps:
  - bash: 
      echo $(tier)
      echo $(target)
    displayName: 'Show value as regular variable'
  
  - bash: 
      echo $TIER
      echo $TARGET
    displayName: 'Show value as env variable'
    
  - bash:
     script: $(SECRETVAR)

