pool:
 vmImage: 'ubuntu-latest'

variables:
 - group: GroupVariable1

steps:
  - bash: 
      echo "var1 $(var1)"
      echo "var2 $(var2)"
    displayName: 'Show value as regular variable grom group'
  
  - bash: 
      echo $VAR1
      echo $VAR2
    displayName: 'Show value as env variable'
    
  - bash:
     echo $mysec
      echo $(SECRETVAR)
    env:
     mysec: $(SECRETVAR)

